import type { WoodboxApi } from '@shared/types/api';
import { request, subscribe } from './ipc';

export const api: WoodboxApi = {
  connections: {
    list: request('@get:config_connections_saved'),
    get: request('@get:config_connection_saved'),
    add: request('@add:config_connections_saved'),
    edit: request('@edit:config_connections_saved'),
    remove: request('@remove:config_connections_saved'),
    test: request('@get:test_connection'),
    close: request('@get:close_connection'),
    getInfo: request('@get:connection_info'),
    previewImport: request('@post:preview_import_connections_from_source'),
    import: request('@post:import_connections_from_source'),
  },
  projects: {
    list: request('@get:projects'),
    add: request('@add:projects'),
    edit: request('@edit:projects'),
    remove: request('@remove:projects'),
  },
  scripts: {
    list: request('@get:scripts_meta'),
    getContent: request('@get:script_content'),
    add: request('@add:scripts'),
    edit: request('@patch:scripts'),
    remove: request('@remove:scripts'),
  },
  snippets: {
    list: request('@get:snippets'),
    add: request('@add:snippets'),
    edit: request('@edit:snippets'),
    remove: request('@remove:snippets'),
  },
  aiProviders: {
    list: request('@get:ai_providers'),
    add: request('@add:ai_providers'),
    edit: request('@edit:ai_providers'),
    remove: request('@remove:ai_providers'),
    test: request('@post:test_ai_provider'),
  },
  aiChats: {
    list: request('@get:ai_chats'),
    add: request('@add:ai_chats'),
    edit: request('@edit:ai_chats'),
    remove: request('@remove:ai_chats'),
    appendMessages: request('@post:append_ai_chat_messages'),
    sendMessage: request('@post:ai_chat_message'),
    cancelMessage: request('@post:cancel_ai_chat_message'),
  },
  codex: {
    getAccount: request('@get:codex_chatgpt_account'),
    startLogin: request('@post:codex_chatgpt_login'),
    logout: request('@post:codex_chatgpt_logout'),
  },
  reactNativeBridge: {
    getStatus: request('@get:react_native_bridge_status'),
    getSessions: request('@get:react_native_bridge_sessions'),
    start: request('@post:react_native_bridge_start_gateway'),
    stop: request('@post:react_native_bridge_stop_gateway'),
    onEvent: subscribe('@event:react_native_bridge_event'),
    onSessionConnected: subscribe('@event:react_native_bridge_session_connected'),
    onSessionDisconnected: subscribe('@event:react_native_bridge_session_disconnected'),
  },
  database: {
    getDialects: request('@get:dialects'),
    getTableData: request('@get:table_data'),
    getTableRowsCount: request('@get:table_rows_count'),
    getQueryRowsCount: request('@get:query_rows_count'),
    getExportPreview: request('@get:export_data_preview'),
    getTableColumns: request('@get:table_columns'),
    getColumnTypes: request('@get:column_types'),
    getTableReferences: request('@get:table_references'),
    getTableUsedAsReference: request('@get:table_used_as_reference'),
    getTableRestrictions: request('@get:table_restrictions'),
    getTableDefinition: request('@get:table_definition'),
    getTableIndexes: request('@get:table_indexes'),
    getTableTriggers: request('@get:table_triggers'),
    getFunctionDefinition: request('@get:function_definition'),
    runSql: request('@post:run_sql'),
    runExplainSql: request('@post:run_explain_sql'),
    exportData: request('@post:export_data'),
    importTableData: request('@post:import_table_data'),
    cancelRunSql: request('@post:cancel_run_sql'),
    getServerOutput: request('@get:server_output'),
    clearServerOutput: request('@delete:server_output'),
    getProcessList: request('@get:process_list'),
    cancelProcess: request('@post:cancel_process'),
    compare: request('@post:compare_databases'),
    onServerOutput: subscribe('@event:server_output'),
  },
  dialogs: {
    selectSqliteFile: request('@dialog:select_sqlite_file'),
    selectDbeaverExportFile: request('@dialog:select_dbeaver_export_file'),
    selectSslFile: request('@dialog:select_ssl_file'),
    selectSshKey: request('@dialog:select_ssh_key'),
  },
  updates: {
    download: request('@post:download_update'),
    quitAndInstall: request('@post:quit_and_install_update'),
    onAvailable: subscribe('@event:update_available'),
    onProgress: subscribe('@event:update_download_progress'),
    onDownloaded: subscribe('@event:update_downloaded'),
    onError: subscribe('@event:update_error'),
  },
};
