export const ROW_HEIGHT = 35;
export const MAX_COLUMN_SIZE = 760;
export const DEFAULT_COLUMN_SIZE = 200;
export const ROW_NUMBER_COLUMN_WIDTH = 56;
export const MIN_ANALYSIS_FIELD_COLUMN_WIDTH = 96;
export const MIN_ANALYSIS_VALUE_COLUMN_WIDTH = 160;
