import type { ITheme } from '../theme';

const amberTheme: ITheme = {
  name: 'woodbox-amber',
  welcome: {
    color: '#edecee',
    backgroundColor: '#1f1b17',
  },
  sideBar: {
    menuBar: {
      color: '#edecee',
      backgroundColor: '#1f1b17',
      ascentColor: '#e6bf75',
    },
    color: '#edecee',
    backgroundColor: '#1f1b17',
    fieldColor: '#edecee',
    fieldPlaceholderColor: '#edecee',
    fieldBackgroundColor: '#302820',
    cardBackgroundColor: '#302820',
    fieldLabelColor: '#edecee',
    borderColor: '#17120d',
    borderMutedColor: '#3838387f',
    selectedBackgroundColor: '#302d3a',
    panelBackgroundColor: '#29231c',
    neutralButtonColor: '#edecee',
    neutralButtonBackgroundColor: '#6d6d6d',
    dangerButtonColor: '#edecee',
    dangerButtonBackgroundColor: '#ff6767',
  },
  mainTab: {
    bar: {
      backgroundColor: '#1f1b17',
      borderColor: '#17120d',
    },
    color: '#edecee',
    backgroundColor: '#1f1b17',
    ascentColor: '#e6bf75',
    borderColor: '#17120d',
    hoverBackgroundColor: '#302820',
    draggingBackgroundColor: '#302820',
    editorShadowColor: '#00000052',
    groupColors: [
      '#8fc8d8',
      '#ff6767',
      '#ffcf8a',
      '#e6bf75',
      '#d6a45f',
      '#e7a98d',
      '#c58a35',
      '#b9893b',
    ],
  },
  toast: {
    success: {
      color: '#edecee',
      backgroundColor: '#b9893b',
    },
    warn: {
      color: '#edecee',
      backgroundColor: '#c58a35',
    },
    error: {
      color: '#edecee',
      backgroundColor: '#E73C3C',
    },
    shadowColor: '#00000052',
    iconBackgroundColor: '#44475a3d',
  },
  contextMenu: {
    color: '#edecee',
    backgroundColor: '#251d16',
    borderColor: '#1f1b17',
  },
  editor: {
    lineNumberColor: '#6d6d6d',
    currentLineNumberColor: '#edecee',
    cursorColor: '#edecee',
    color: '#edecee',
    backgroundColor: '#1f1b17',
    selectionColor: '#5f45257f',
    keywordColor: '#d6a45f',
    identifierColor: '#ffcf8a',
    stringColor: '#e6bf75',
    numberColor: '#e7a98d',
    currentLineBackgroundColor: '#44475a3d',
  },
  table: {
    borderColor: '#3838387f',
    colorHeader: '#edecee',
    backgroundColorHeader: '#1f1b17',
    backgroundColor: '#1f1b17',
    backgroundColorRowEven: '#1f1b17',
    colorRowEven: '#edecee',
    colorRowOdd: '#edecee',
    backgroundColorRowOdd: '#302820',
    backgroundColorColumnEdited: '#ffcf8a',
    colorColumnEdited: '#1f1b17',
    selectedColor: '#edecee',
    selectedBackgroundColor: '#72a1ff59',
    selectedBorderColor: '#8fc8d8',
    backgroundColorRowNew: 'color-mix(in srgb, #e6bf75 24%, transparent)',
    backgroundColorRowRemoved: '#ff676733',
  },
  modal: {
    color: '#edecee',
    backgroundColor: '#1f1b17',
    fieldColor: '#edecee',
    fieldBackgroundColor: '#302820',
    fieldLabelColor: '#edecee',
    saveButtonColor: '#1f1b17',
    saveButtonBackgroundColor: '#e6bf75',
    cancelButtonColor: '#1f1b17',
    cancelButtonBackgroundColor: '#ff6767',
    testButtonColor: '#1f1b17',
    testButtonBackgroundColor: '#ffcf8a',
    overlayColor: '#00000080',
    borderColor: '#3838387f',
    panelBackgroundColor: '#302820',
    mutedColor: '#6d6d6d',
    neutralButtonColor: '#edecee',
    neutralButtonBackgroundColor: '#6d6d6d',
    dangerButtonColor: '#edecee',
    dangerButtonBackgroundColor: '#ff6767',
  },
  button: {
    hoverBackgroundColor: '#302820',
    activeColor: '#e6bf75',
  },
  autocomplete: {
    backgroundColor: '#302820',
    hoverBackgroundColor: '#302d3a',
    selectedBackgroundColor: '#72a1ff59',
    activeBackgroundColor: '#5f45257f',
    borderColor: '#3838387f',
    shadowColor: '#00000033',
    blank: {
      hoverBackgroundColor: '#44475a3d',
      selectedBackgroundColor: '#302820',
      activeBackgroundColor: '#302820',
      borderColor: '#3838387f',
      shadowColor: '#00000033',
    },
  },
  field: {
    requiredColor: '#ff6767',
    borderColor: '#3838387f',
    mutedColor: '#6d6d6d',
  },
  loaders: {
    overlayBackgroundColor: '#00000080',
    spinnerBackgroundColor: '#44475a3d',
    barColors: [
      '#d6a45f',
      '#8fc8d8',
      '#e6bf75',
      '#ffcf8a',
      '#c58a35',
      '#e7a98d',
    ],
  },
  settings: {
    menuBackgroundColor: '#29231c',
    menuHoverBackgroundColor: '#302820',
    inactiveMenuColor: '#3838387f',
    mutedColor: '#6d6d6d',
    optionHoverBackgroundColor: '#302820',
    themeBorderColor: '#3838387f',
    themePanelBackgroundColor: '#29231c',
    themeHoverBackgroundColor: '#302820',
    importBorderColor: '#3838387f',
    importBackgroundColor: '#29231c',
    importMutedColor: '#6d6d6d',
    importWarningColor: '#ffcf8a',
  },
  centralSearch: {
    overlayColor: '#0000007a',
    borderColor: '#3838387f',
    shadowColor: '#00000052',
    subtleBackgroundColor: '#44475a3d',
    hoverBackgroundColor: '#302820',
    mutedColor: '#6d6d6d',
    dropdownBorderColor: '#3838387f',
  },
  aiChat: {
    cardBackgroundColor: '#302820',
    mutedColor: '#6d6d6d',
    sendBackgroundColor: '#e6bf75',
    sendColor: '#1f1b17',
    sendDisabledBackgroundColor: '#6d6d6d',
    sendDisabledColor: '#edecee',
    queryPendingColor: '#ffcf8a',
    queryApprovedColor: '#e6bf75',
    queryRejectedColor: '#ff6767',
    dropdownBackgroundColor: '#302820',
    neutralButtonColor: '#edecee',
    neutralButtonBackgroundColor: '#6d6d6d',
    dangerButtonColor: '#edecee',
    dangerButtonBackgroundColor: '#ff6767',
  },
  feedback: {
    errorBorderColor: '#E73C3C',
    errorAccentColor: '#ff6767',
    errorBackgroundColor: '#44475a3d',
    errorMessageBackgroundColor: '#44475a3d',
    warningBorderColor: '#c58a35',
    warningBackgroundColor: '#d2992233',
  },
  tableInfo: {
    tab: {
      bar: {
        backgroundColor: '#1f1b17',
        borderColor: '#17120d',
      },
      color: '#edecee',
      backgroundColor: '#1f1b17',
      ascentColor: '#d6a45f',
      borderColor: '#17120d',
    },
    properties: {
      tab: {
        bar: {
          backgroundColor: '#1f1b17',
          borderColor: '#17120d',
        },
        color: '#edecee',
        backgroundColor: '#1f1b17',
        ascentColor: '#ffcf8a',
        borderColor: '#17120d',
      },
      header: {
        backgroundColor: '#1f1b17',
        fieldColor: '#edecee',
        fieldBackgroundColor: '#302820',
        fieldLabelColor: '#edecee',
      },
      bar: {
        backgroundColor: '#1f1b17',
        color: '#edecee',
        borderColor: '#17120d',
      },
    },
    data: {
      bar: {
        color: '#edecee',
        backgroundColor: '#29231c',
        fieldColor: '#edecee',
        fieldBackgroundColor: '#302820',
        borderColor: '#17120d',
      },
    },
  },
  queryEditor: {
    tab: {
      bar: {
        backgroundColor: '#1f1b17',
        borderColor: '#17120d',
      },
      color: '#edecee',
      backgroundColor: '#1f1b17',
      ascentColor: '#ffcf8a',
      borderColor: '#17120d',
    },
    bar: {
      backgroundColor: '#29231c',
      fieldColor: '#edecee',
      color: '#edecee',
      fieldBackgroundColor: '#302820',
      fieldPlaceholderColor: '#edecee',
      borderColor: '#17120d',
    },
    error: {
      borderColor: '#E73C3C',
      accentColor: '#ff6767',
      backgroundColor: '#44475a3d',
      messageBackgroundColor: '#44475a3d',
      messageColor: '#edecee',
      mutedColor: '#6d6d6d',
    },
    explain: {
      mutedColor: '#6d6d6d',
      surfaceColor: '#302820',
      warnColor: '#ffcf8a',
      dangerColor: '#ff6767',
    },
    serverOutput: {
      backgroundColor: '#44475a3d',
    },
    capture: {
      activeColor: '#ff6767',
      modifiedColor: '#ffcf8a',
    },
  },
};

export default amberTheme;
