import type { ITheme } from '../theme';

const defaultTheme: ITheme = {
  name: 'default-theme',
  welcome: {
    color: '#edecee',
    backgroundColor: '#1c1b22',
  },
  sideBar: {
    menuBar: {
      color: '#edecee',
      backgroundColor: '#1c1b22',
      ascentColor: '#61ffca',
    },
    color: '#edecee',
    backgroundColor: '#1c1b22',
    fieldColor: '#edecee',
    fieldPlaceholderColor: '#edecee',
    fieldBackgroundColor: '#242329',
    cardBackgroundColor: '#242329',
    fieldLabelColor: '#edecee',
    borderColor: '#191622',
    borderMutedColor: '#3838387f',
    selectedBackgroundColor: '#302d3a',
    panelBackgroundColor: '#1f1f26',
    neutralButtonColor: '#edecee',
    neutralButtonBackgroundColor: '#6d6d6d',
    dangerButtonColor: '#edecee',
    dangerButtonBackgroundColor: '#ff6767',
  },
  mainTab: {
    bar: {
      backgroundColor: '#1c1b22',
      borderColor: '#191622',
    },
    color: '#edecee',
    backgroundColor: '#1c1b22',
    ascentColor: '#61ffca',
    borderColor: '#191622',
    hoverBackgroundColor: '#242329',
    draggingBackgroundColor: '#242329',
    editorShadowColor: '#00000052',
    groupColors: [
      '#82e2ff',
      '#ff6767',
      '#ffca85',
      '#61ffca',
      '#a277ff',
      '#f694ff',
      '#E79E3F',
      '#54C59F',
    ],
  },
  toast: {
    success: {
      color: '#edecee',
      backgroundColor: '#54C59F',
    },
    warn: {
      color: '#edecee',
      backgroundColor: '#E79E3F',
    },
    error: {
      color: '#edecee',
      backgroundColor: '#E73C3C',
    },
    shadowColor: '#00000052',
    iconBackgroundColor: '#44475a3d',
  },
  contextMenu: {
    color: '#edecee',
    backgroundColor: '#1b1727',
    borderColor: '#1c1b22',
  },
  editor: {
    lineNumberColor: '#6d6d6d',
    currentLineNumberColor: '#edecee',
    cursorColor: '#edecee',
    color: '#edecee',
    backgroundColor: '#1c1b22',
    selectionColor: '#3d375e7f',
    keywordColor: '#a277ff',
    identifierColor: '#ffca85',
    stringColor: '#61ffca',
    numberColor: '#f694ff',
    currentLineBackgroundColor: '#44475a3d',
  },
  table: {
    borderColor: '#3838387f',
    colorHeader: '#edecee',
    backgroundColorHeader: '#1c1b22',
    backgroundColor: '#1c1b22',
    backgroundColorRowEven: '#1c1b22',
    colorRowEven: '#edecee',
    colorRowOdd: '#edecee',
    backgroundColorRowOdd: '#242329',
    backgroundColorColumnEdited: '#ffca85',
    colorColumnEdited: '#1c1b22',
    selectedColor: '#edecee',
    selectedBackgroundColor: '#72a1ff59',
    selectedBorderColor: '#82e2ff',
    backgroundColorRowNew: 'color-mix(in srgb, #61ffca 24%, transparent)',
    backgroundColorRowRemoved: '#ff676733',
  },
  modal: {
    color: '#edecee',
    backgroundColor: '#1c1b22',
    fieldColor: '#edecee',
    fieldBackgroundColor: '#242329',
    fieldLabelColor: '#edecee',
    saveButtonColor: '#1c1b22',
    saveButtonBackgroundColor: '#61ffca',
    cancelButtonColor: '#1c1b22',
    cancelButtonBackgroundColor: '#ff6767',
    testButtonColor: '#1c1b22',
    testButtonBackgroundColor: '#ffca85',
    overlayColor: '#00000080',
    borderColor: '#3838387f',
    panelBackgroundColor: '#242329',
    mutedColor: '#6d6d6d',
    neutralButtonColor: '#edecee',
    neutralButtonBackgroundColor: '#6d6d6d',
    dangerButtonColor: '#edecee',
    dangerButtonBackgroundColor: '#ff6767',
  },
  button: {
    hoverBackgroundColor: '#242329',
    activeColor: '#61ffca',
  },
  autocomplete: {
    backgroundColor: '#242329',
    hoverBackgroundColor: '#302d3a',
    selectedBackgroundColor: '#72a1ff59',
    activeBackgroundColor: '#3d375e7f',
    borderColor: '#3838387f',
    shadowColor: '#00000033',
    blank: {
      hoverBackgroundColor: '#44475a3d',
      selectedBackgroundColor: '#242329',
      activeBackgroundColor: '#242329',
      borderColor: '#3838387f',
      shadowColor: '#00000033',
    },
  },
  field: {
    requiredColor: '#ff6767',
    borderColor: '#3838387f',
    mutedColor: '#6d6d6d',
  },
  loaders: {
    overlayBackgroundColor: '#00000080',
    spinnerBackgroundColor: '#44475a3d',
    barColors: [
      '#a277ff',
      '#82e2ff',
      '#61ffca',
      '#ffca85',
      '#E79E3F',
      '#f694ff',
    ],
  },
  settings: {
    menuBackgroundColor: '#1f1f26',
    menuHoverBackgroundColor: '#242329',
    inactiveMenuColor: '#3838387f',
    mutedColor: '#6d6d6d',
    optionHoverBackgroundColor: '#242329',
    themeBorderColor: '#3838387f',
    themePanelBackgroundColor: '#1f1f26',
    themeHoverBackgroundColor: '#242329',
    importBorderColor: '#3838387f',
    importBackgroundColor: '#1f1f26',
    importMutedColor: '#6d6d6d',
    importWarningColor: '#ffca85',
  },
  centralSearch: {
    overlayColor: '#0000007a',
    borderColor: '#3838387f',
    shadowColor: '#00000052',
    subtleBackgroundColor: '#44475a3d',
    hoverBackgroundColor: '#242329',
    mutedColor: '#6d6d6d',
    dropdownBorderColor: '#3838387f',
  },
  aiChat: {
    cardBackgroundColor: '#242329',
    mutedColor: '#6d6d6d',
    sendBackgroundColor: '#61ffca',
    sendColor: '#1c1b22',
    sendDisabledBackgroundColor: '#6d6d6d',
    sendDisabledColor: '#edecee',
    queryPendingColor: '#ffca85',
    queryApprovedColor: '#61ffca',
    queryRejectedColor: '#ff6767',
    dropdownBackgroundColor: '#242329',
    neutralButtonColor: '#edecee',
    neutralButtonBackgroundColor: '#6d6d6d',
    dangerButtonColor: '#edecee',
    dangerButtonBackgroundColor: '#ff6767',
  },
  feedback: {
    errorBorderColor: '#E73C3C',
    errorAccentColor: '#ff6767',
    errorBackgroundColor: '#44475a3d',
    errorMessageBackgroundColor: '#44475a3d',
    warningBorderColor: '#E79E3F',
    warningBackgroundColor: '#d2992233',
  },
  tableInfo: {
    tab: {
      bar: {
        backgroundColor: '#1c1b22',
        borderColor: '#191622',
      },
      color: '#edecee',
      backgroundColor: '#1c1b22',
      ascentColor: '#a277ff',
      borderColor: '#191622',
    },
    properties: {
      tab: {
        bar: {
          backgroundColor: '#1c1b22',
          borderColor: '#191622',
        },
        color: '#edecee',
        backgroundColor: '#1c1b22',
        ascentColor: '#ffca85',
        borderColor: '#191622',
      },
      header: {
        backgroundColor: '#1c1b22',
        fieldColor: '#edecee',
        fieldBackgroundColor: '#242329',
        fieldLabelColor: '#edecee',
      },
      bar: {
        backgroundColor: '#1c1b22',
        color: '#edecee',
        borderColor: '#191622',
      },
    },
    data: {
      bar: {
        color: '#edecee',
        backgroundColor: '#1f1f26',
        fieldColor: '#edecee',
        fieldBackgroundColor: '#242329',
        borderColor: '#191622',
      },
    },
  },
  queryEditor: {
    tab: {
      bar: {
        backgroundColor: '#1c1b22',
        borderColor: '#191622',
      },
      color: '#edecee',
      backgroundColor: '#1c1b22',
      ascentColor: '#ffca85',
      borderColor: '#191622',
    },
    bar: {
      backgroundColor: '#1f1f26',
      fieldColor: '#edecee',
      color: '#edecee',
      fieldBackgroundColor: '#242329',
      fieldPlaceholderColor: '#edecee',
      borderColor: '#191622',
    },
    error: {
      borderColor: '#E73C3C',
      accentColor: '#ff6767',
      backgroundColor: '#44475a3d',
      messageBackgroundColor: '#44475a3d',
      messageColor: '#edecee',
      mutedColor: '#6d6d6d',
    },
    explain: {
      mutedColor: '#6d6d6d',
      surfaceColor: '#242329',
      warnColor: '#ffca85',
      dangerColor: '#ff6767',
    },
    serverOutput: {
      backgroundColor: '#44475a3d',
    },
    capture: {
      activeColor: '#ff6767',
      modifiedColor: '#ffca85',
    },
  },
};

export default defaultTheme;
