import type { ITheme } from '../theme';

const catppuccinLatteTheme: ITheme = {
  name: 'catppuccin-latte',
  welcome: {
    color: '#4c4f69',
    backgroundColor: '#eff1f5',
  },
  sideBar: {
    menuBar: {
      color: '#4c4f69',
      backgroundColor: '#e6e9ef',
      ascentColor: '#40a02b',
    },
    color: '#4c4f69',
    backgroundColor: '#e6e9ef',
    fieldColor: '#4c4f69',
    fieldPlaceholderColor: '#6c6f85',
    fieldBackgroundColor: '#dce0e8',
    cardBackgroundColor: '#dce0e8',
    fieldLabelColor: '#4c4f69',
    borderColor: '#ccd0da',
    borderMutedColor: '#ccd0da7f',
    selectedBackgroundColor: '#302d3a',
    panelBackgroundColor: '#e6e9ef',
    neutralButtonColor: '#4c4f69',
    neutralButtonBackgroundColor: '#6c6f85',
    dangerButtonColor: '#4c4f69',
    dangerButtonBackgroundColor: '#d20f39',
  },
  mainTab: {
    bar: {
      backgroundColor: '#e6e9ef',
      borderColor: '#ccd0da',
    },
    color: '#4c4f69',
    backgroundColor: '#e6e9ef',
    ascentColor: '#40a02b',
    borderColor: '#ccd0da',
    hoverBackgroundColor: '#dce0e8',
    draggingBackgroundColor: '#dce0e8',
    editorShadowColor: '#00000052',
    groupColors: [
      '#1e66f5',
      '#d20f39',
      '#fe640b',
      '#40a02b',
      '#8839ef',
      '#ea76cb',
      '#df4f00',
      '#2b8a1f',
    ],
  },
  toast: {
    success: {
      color: '#4c4f69',
      backgroundColor: '#2b8a1f',
    },
    warn: {
      color: '#4c4f69',
      backgroundColor: '#df4f00',
    },
    error: {
      color: '#4c4f69',
      backgroundColor: '#b70f2f',
    },
    shadowColor: '#00000052',
    iconBackgroundColor: '#dce0e83d',
  },
  contextMenu: {
    color: '#4c4f69',
    backgroundColor: '#eff1f5',
    borderColor: '#ccd0da',
  },
  editor: {
    lineNumberColor: '#6c6f85',
    currentLineNumberColor: '#4c4f69',
    cursorColor: '#4c4f69',
    color: '#4c4f69',
    backgroundColor: '#e6e9ef',
    selectionColor: '#cba6f77f',
    keywordColor: '#8839ef',
    identifierColor: '#fe640b',
    stringColor: '#40a02b',
    numberColor: '#ea76cb',
    currentLineBackgroundColor: '#eff1f5',
  },
  table: {
    borderColor: '#ccd0da',
    colorHeader: '#4c4f69',
    backgroundColorHeader: '#e6e9ef',
    backgroundColor: '#e6e9ef',
    backgroundColorRowEven: '#eff1f5',
    colorRowEven: '#4c4f69',
    colorRowOdd: '#4c4f69',
    backgroundColorRowOdd: '#e6e9ef',
    backgroundColorColumnEdited: '#fe640b',
    colorColumnEdited: '#e6e9ef',
    selectedColor: '#4c4f69',
    selectedBackgroundColor: '#1e66f533',
    selectedBorderColor: '#1e66f5',
    backgroundColorRowNew: 'color-mix(in srgb, #40a02b 24%, transparent)',
    backgroundColorRowRemoved: '#ff676733',
  },
  modal: {
    color: '#4c4f69',
    backgroundColor: '#e6e9ef',
    fieldColor: '#4c4f69',
    fieldBackgroundColor: '#dce0e8',
    fieldLabelColor: '#4c4f69',
    saveButtonColor: '#e6e9ef',
    saveButtonBackgroundColor: '#40a02b',
    cancelButtonColor: '#e6e9ef',
    cancelButtonBackgroundColor: '#d20f39',
    testButtonColor: '#e6e9ef',
    testButtonBackgroundColor: '#fe640b',
    overlayColor: '#00000080',
    borderColor: '#ccd0da7f',
    panelBackgroundColor: '#dce0e8',
    mutedColor: '#6c6f85',
    neutralButtonColor: '#4c4f69',
    neutralButtonBackgroundColor: '#6c6f85',
    dangerButtonColor: '#4c4f69',
    dangerButtonBackgroundColor: '#d20f39',
  },
  button: {
    hoverBackgroundColor: '#dce0e8',
    activeColor: '#40a02b',
  },
  autocomplete: {
    backgroundColor: '#dce0e8',
    hoverBackgroundColor: '#302d3a',
    selectedBackgroundColor: '#1e66f533',
    activeBackgroundColor: '#cba6f77f',
    borderColor: '#ccd0da7f',
    shadowColor: '#00000033',
    blank: {
      hoverBackgroundColor: '#dce0e83d',
      selectedBackgroundColor: '#dce0e8',
      activeBackgroundColor: '#dce0e8',
      borderColor: '#ccd0da7f',
      shadowColor: '#00000033',
    },
  },
  field: {
    requiredColor: '#d20f39',
    borderColor: '#ccd0da7f',
    mutedColor: '#6c6f85',
  },
  loaders: {
    overlayBackgroundColor: '#00000080',
    spinnerBackgroundColor: '#dce0e83d',
    barColors: [
      '#8839ef',
      '#1e66f5',
      '#40a02b',
      '#fe640b',
      '#df4f00',
      '#ea76cb',
    ],
  },
  settings: {
    menuBackgroundColor: '#e6e9ef',
    menuHoverBackgroundColor: '#dce0e8',
    inactiveMenuColor: '#ccd0da7f',
    mutedColor: '#6c6f85',
    optionHoverBackgroundColor: '#dce0e8',
    themeBorderColor: '#ccd0da7f',
    themePanelBackgroundColor: '#e6e9ef',
    themeHoverBackgroundColor: '#dce0e8',
    importBorderColor: '#ccd0da7f',
    importBackgroundColor: '#e6e9ef',
    importMutedColor: '#6c6f85',
    importWarningColor: '#fe640b',
  },
  centralSearch: {
    overlayColor: '#0000007a',
    borderColor: '#ccd0da7f',
    shadowColor: '#00000052',
    subtleBackgroundColor: '#dce0e83d',
    hoverBackgroundColor: '#dce0e8',
    mutedColor: '#6c6f85',
    dropdownBorderColor: '#ccd0da7f',
  },
  aiChat: {
    cardBackgroundColor: '#dce0e8',
    mutedColor: '#6c6f85',
    sendBackgroundColor: '#40a02b',
    sendColor: '#eff1f5',
    sendDisabledBackgroundColor: '#6c6f85',
    sendDisabledColor: '#4c4f69',
    queryPendingColor: '#fe640b',
    queryApprovedColor: '#40a02b',
    queryRejectedColor: '#d20f39',
    dropdownBackgroundColor: '#dce0e8',
    neutralButtonColor: '#4c4f69',
    neutralButtonBackgroundColor: '#6c6f85',
    dangerButtonColor: '#4c4f69',
    dangerButtonBackgroundColor: '#d20f39',
  },
  feedback: {
    errorBorderColor: '#b70f2f',
    errorAccentColor: '#d20f39',
    errorBackgroundColor: '#dce0e83d',
    errorMessageBackgroundColor: '#dce0e83d',
    warningBorderColor: '#df4f00',
    warningBackgroundColor: '#d2992233',
  },
  tableInfo: {
    tab: {
      bar: {
        backgroundColor: '#e6e9ef',
        borderColor: '#ccd0da',
      },
      color: '#4c4f69',
      backgroundColor: '#e6e9ef',
      ascentColor: '#8839ef',
      borderColor: '#ccd0da',
    },
    properties: {
      tab: {
        bar: {
          backgroundColor: '#e6e9ef',
          borderColor: '#ccd0da',
        },
        color: '#4c4f69',
        backgroundColor: '#e6e9ef',
        ascentColor: '#fe640b',
        borderColor: '#ccd0da',
      },
      header: {
        backgroundColor: '#e6e9ef',
        fieldColor: '#4c4f69',
        fieldBackgroundColor: '#dce0e8',
        fieldLabelColor: '#4c4f69',
      },
      bar: {
        backgroundColor: '#dce0e8',
        color: '#4c4f69',
        borderColor: '#ccd0da',
      },
    },
    data: {
      bar: {
        color: '#4c4f69',
        backgroundColor: '#dce0e8',
        fieldColor: '#4c4f69',
        fieldBackgroundColor: '#eff1f5',
        borderColor: '#ccd0da',
      },
    },
  },
  queryEditor: {
    tab: {
      bar: {
        backgroundColor: '#e6e9ef',
        borderColor: '#ccd0da',
      },
      color: '#4c4f69',
      backgroundColor: '#e6e9ef',
      ascentColor: '#fe640b',
      borderColor: '#ccd0da',
    },
    bar: {
      backgroundColor: '#dce0e8',
      fieldColor: '#4c4f69',
      color: '#4c4f69',
      fieldBackgroundColor: '#eff1f5',
      fieldPlaceholderColor: '#6c6f85',
      borderColor: '#ccd0da',
    },
    error: {
      borderColor: '#b70f2f',
      accentColor: '#d20f39',
      backgroundColor: '#dce0e83d',
      messageBackgroundColor: '#dce0e83d',
      messageColor: '#4c4f69',
      mutedColor: '#6c6f85',
    },
    explain: {
      mutedColor: '#6c6f85',
      surfaceColor: '#dce0e8',
      warnColor: '#fe640b',
      dangerColor: '#d20f39',
    },
    serverOutput: {
      backgroundColor: '#dce0e83d',
    },
    capture: {
      activeColor: '#d20f39',
      modifiedColor: '#fe640b',
    },
  },
};

export default catppuccinLatteTheme;
