import type { ITheme } from '../theme';

const githubLightTheme: ITheme = {
  name: 'github-light',
  welcome: {
    color: '#24292f',
    backgroundColor: '#f3f6fa',
  },
  sideBar: {
    menuBar: {
      color: '#24292f',
      backgroundColor: '#e9eef5',
      ascentColor: '#1a7f37',
    },
    color: '#24292f',
    backgroundColor: '#e9eef5',
    fieldColor: '#24292f',
    fieldPlaceholderColor: '#57606a',
    fieldBackgroundColor: '#dfe6ef',
    cardBackgroundColor: '#dfe6ef',
    fieldLabelColor: '#24292f',
    borderColor: '#c6ced8',
    borderMutedColor: '#c6ced87f',
    selectedBackgroundColor: '#302d3a',
    panelBackgroundColor: '#e9eef5',
    neutralButtonColor: '#24292f',
    neutralButtonBackgroundColor: '#57606a',
    dangerButtonColor: '#24292f',
    dangerButtonBackgroundColor: '#cf222e',
  },
  mainTab: {
    bar: {
      backgroundColor: '#e9eef5',
      borderColor: '#c6ced8',
    },
    color: '#24292f',
    backgroundColor: '#e9eef5',
    ascentColor: '#1a7f37',
    borderColor: '#c6ced8',
    hoverBackgroundColor: '#dfe6ef',
    draggingBackgroundColor: '#dfe6ef',
    editorShadowColor: '#00000052',
    groupColors: [
      '#0969da',
      '#cf222e',
      '#9a6700',
      '#1a7f37',
      '#8250df',
      '#cf222e',
      '#7d4e00',
      '#116329',
    ],
  },
  toast: {
    success: {
      color: '#24292f',
      backgroundColor: '#116329',
    },
    warn: {
      color: '#24292f',
      backgroundColor: '#7d4e00',
    },
    error: {
      color: '#24292f',
      backgroundColor: '#a40e26',
    },
    shadowColor: '#00000052',
    iconBackgroundColor: '#cfd8e33d',
  },
  contextMenu: {
    color: '#24292f',
    backgroundColor: '#f3f6fa',
    borderColor: '#c6ced8',
  },
  editor: {
    lineNumberColor: '#57606a',
    currentLineNumberColor: '#24292f',
    cursorColor: '#24292f',
    color: '#24292f',
    backgroundColor: '#e9eef5',
    selectionColor: '#d8b9ff7f',
    keywordColor: '#8250df',
    identifierColor: '#9a6700',
    stringColor: '#1a7f37',
    numberColor: '#cf222e',
    currentLineBackgroundColor: '#f3f6fa',
  },
  table: {
    borderColor: '#c6ced8',
    colorHeader: '#24292f',
    backgroundColorHeader: '#e9eef5',
    backgroundColor: '#e9eef5',
    backgroundColorRowEven: '#f3f6fa',
    colorRowEven: '#24292f',
    colorRowOdd: '#24292f',
    backgroundColorRowOdd: '#e9eef5',
    backgroundColorColumnEdited: '#9a6700',
    colorColumnEdited: '#e9eef5',
    selectedColor: '#24292f',
    selectedBackgroundColor: '#0969da33',
    selectedBorderColor: '#0969da',
    backgroundColorRowNew: 'color-mix(in srgb, #1a7f37 24%, transparent)',
    backgroundColorRowRemoved: '#ff676733',
  },
  modal: {
    color: '#24292f',
    backgroundColor: '#e9eef5',
    fieldColor: '#24292f',
    fieldBackgroundColor: '#dfe6ef',
    fieldLabelColor: '#24292f',
    saveButtonColor: '#e9eef5',
    saveButtonBackgroundColor: '#1a7f37',
    cancelButtonColor: '#e9eef5',
    cancelButtonBackgroundColor: '#cf222e',
    testButtonColor: '#e9eef5',
    testButtonBackgroundColor: '#9a6700',
    overlayColor: '#00000080',
    borderColor: '#c6ced87f',
    panelBackgroundColor: '#dfe6ef',
    mutedColor: '#57606a',
    neutralButtonColor: '#24292f',
    neutralButtonBackgroundColor: '#57606a',
    dangerButtonColor: '#24292f',
    dangerButtonBackgroundColor: '#cf222e',
  },
  button: {
    hoverBackgroundColor: '#dfe6ef',
    activeColor: '#1a7f37',
  },
  autocomplete: {
    backgroundColor: '#dfe6ef',
    hoverBackgroundColor: '#302d3a',
    selectedBackgroundColor: '#0969da33',
    activeBackgroundColor: '#d8b9ff7f',
    borderColor: '#c6ced87f',
    shadowColor: '#00000033',
    blank: {
      hoverBackgroundColor: '#cfd8e33d',
      selectedBackgroundColor: '#dfe6ef',
      activeBackgroundColor: '#dfe6ef',
      borderColor: '#c6ced87f',
      shadowColor: '#00000033',
    },
  },
  field: {
    requiredColor: '#cf222e',
    borderColor: '#c6ced87f',
    mutedColor: '#57606a',
  },
  loaders: {
    overlayBackgroundColor: '#00000080',
    spinnerBackgroundColor: '#cfd8e33d',
    barColors: [
      '#8250df',
      '#0969da',
      '#1a7f37',
      '#9a6700',
      '#7d4e00',
      '#cf222e',
    ],
  },
  settings: {
    menuBackgroundColor: '#e9eef5',
    menuHoverBackgroundColor: '#dfe6ef',
    inactiveMenuColor: '#c6ced87f',
    mutedColor: '#57606a',
    optionHoverBackgroundColor: '#dfe6ef',
    themeBorderColor: '#c6ced87f',
    themePanelBackgroundColor: '#e9eef5',
    themeHoverBackgroundColor: '#dfe6ef',
    importBorderColor: '#c6ced87f',
    importBackgroundColor: '#e9eef5',
    importMutedColor: '#57606a',
    importWarningColor: '#9a6700',
  },
  centralSearch: {
    overlayColor: '#0000007a',
    borderColor: '#c6ced87f',
    shadowColor: '#00000052',
    subtleBackgroundColor: '#cfd8e33d',
    hoverBackgroundColor: '#dfe6ef',
    mutedColor: '#57606a',
    dropdownBorderColor: '#c6ced87f',
  },
  aiChat: {
    cardBackgroundColor: '#dfe6ef',
    mutedColor: '#57606a',
    sendBackgroundColor: '#1a7f37',
    sendColor: '#f3f6fa',
    sendDisabledBackgroundColor: '#57606a',
    sendDisabledColor: '#24292f',
    queryPendingColor: '#9a6700',
    queryApprovedColor: '#1a7f37',
    queryRejectedColor: '#cf222e',
    dropdownBackgroundColor: '#dfe6ef',
    neutralButtonColor: '#24292f',
    neutralButtonBackgroundColor: '#57606a',
    dangerButtonColor: '#24292f',
    dangerButtonBackgroundColor: '#cf222e',
  },
  feedback: {
    errorBorderColor: '#a40e26',
    errorAccentColor: '#cf222e',
    errorBackgroundColor: '#cfd8e33d',
    errorMessageBackgroundColor: '#cfd8e33d',
    warningBorderColor: '#7d4e00',
    warningBackgroundColor: '#d2992233',
  },
  tableInfo: {
    tab: {
      bar: {
        backgroundColor: '#e9eef5',
        borderColor: '#c6ced8',
      },
      color: '#24292f',
      backgroundColor: '#e9eef5',
      ascentColor: '#8250df',
      borderColor: '#c6ced8',
    },
    properties: {
      tab: {
        bar: {
          backgroundColor: '#e9eef5',
          borderColor: '#c6ced8',
        },
        color: '#24292f',
        backgroundColor: '#e9eef5',
        ascentColor: '#9a6700',
        borderColor: '#c6ced8',
      },
      header: {
        backgroundColor: '#e9eef5',
        fieldColor: '#24292f',
        fieldBackgroundColor: '#dfe6ef',
        fieldLabelColor: '#24292f',
      },
      bar: {
        backgroundColor: '#dfe6ef',
        color: '#24292f',
        borderColor: '#c6ced8',
      },
    },
    data: {
      bar: {
        color: '#24292f',
        backgroundColor: '#dfe6ef',
        fieldColor: '#24292f',
        fieldBackgroundColor: '#f3f6fa',
        borderColor: '#c6ced8',
      },
    },
  },
  queryEditor: {
    tab: {
      bar: {
        backgroundColor: '#e9eef5',
        borderColor: '#c6ced8',
      },
      color: '#24292f',
      backgroundColor: '#e9eef5',
      ascentColor: '#9a6700',
      borderColor: '#c6ced8',
    },
    bar: {
      backgroundColor: '#dfe6ef',
      fieldColor: '#24292f',
      color: '#24292f',
      fieldBackgroundColor: '#f3f6fa',
      fieldPlaceholderColor: '#57606a',
      borderColor: '#c6ced8',
    },
    error: {
      borderColor: '#a40e26',
      accentColor: '#cf222e',
      backgroundColor: '#cfd8e33d',
      messageBackgroundColor: '#cfd8e33d',
      messageColor: '#24292f',
      mutedColor: '#57606a',
    },
    explain: {
      mutedColor: '#57606a',
      surfaceColor: '#dfe6ef',
      warnColor: '#9a6700',
      dangerColor: '#cf222e',
    },
    serverOutput: {
      backgroundColor: '#cfd8e33d',
    },
    capture: {
      activeColor: '#cf222e',
      modifiedColor: '#9a6700',
    },
  },
};

export default githubLightTheme;
